### ISSUE TITLE
Rounding issue

### ISSUE THREAD

**Issue by leporo** [matjaz/upnqr#5]
When a pass the amount (znesek) of 4.60 euro to `upnEncode` method, I get a QR code for 4.59 euro. 
I don't really like giving out my cents.

I would suggest using the `Math.round` call in place of `Math.floor` in `formatAmount` function:

```
function formatAmount(amount) {
    return pad(Math.floor(amount * 100).toString(), 11)
}
```

**Comment by matjaz** [comment]
thanks
